version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build-test:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circle-ci
    
      - node/test:
            requires:
              - "node/run"
            filter:
              branches:
                only:
                  - circle-ci