name: Test workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the name
        run: |
          export NAME=Mathias
          echo $NAME
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-ci-cd-esgi" #Must be unique in Heroku
          heroku_email: "pierucci.romain@gmail.com"